config/routes.rb
Rails.application.routes.draw do
  ## 提案する献立の表示＆レシピの表示  2016/10/03追加　井上
  get 'dish' => 'recipe_pages#result'
  get 'recipe/:id' => 'recipe_pages#recipe'
  get 'test' => 'recipe_pages#test'
  ## end

  get 'recipe/:id/fav' => 'recipe_pages#fav'

  get 'manu_disp/menu_disp'
  get 'question_result/question_result'

  post 'menu/question_result' => 'manu_pages#question_result'
  post 'question'=>'manu_pages#question'

  get 'init'=>'manu_pages#init'

  get 'question'=>'manu_pages#question'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'signup' => 'user_pages#regist'

  get 'user_pages/:id/allergies' => 'user_pages#allergies'

  post 'user_pages/:id/allergies/allergiesinput' => 'user_pages#allergiesinput'

  get 'user_pages/:id/favdeleteselect' => 'user_pages#favdeleteselect'

  post 'user_pages/:id/favdeleteselect/favdelete' => 'user_pages#favdelete'

  get 'user_pages/:id/namechange' => 'user_pages#namechange'

  get 'user_pages/:id/newemailinput' => 'user_pages#newemailinput'

  post 'user_pages/:id/emailchange/sentnewmail' => 'user_pages#sentnewmail'

  get 'user_pages/:id/emailchange' => 'user_pages#emailchange', :as => :emailchange

  get 'drawalinput' => 'user_pages#destroyinput'

  post 'drawalconfirm' => 'user_pages#destroyconfirm'

  post 'signup/confirm' => 'user_pages#confirm'

  get 'about' =>'static_pages/about'

  root 'static_pages#home'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :user_pages
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/controllers/manu_pages_controller.rb
class ManuPagesController < ApplicationController


  def init
    #  ログイン済かそうでないかチェック
    #  ログイン済：ユーザDBからアレルギー値を取得し、def questionへ
    #  非ログインの場合はアレルギーをDBから取得し、チェックボックスへ格納
    if logged_in?
      current_user.alvalue
      redirect_to :action => 'question'
    else
      @allergie = Allergy.all
  end

    if params[:back]
      render :text => 'テキスト'
    end
  end


  def question
    #  情報をfindに渡す
    # helper_method :current_user, :logged_in?
    # if logged_in?
    #   current_user.alvalue
    #   redirect_to :action => 'question'
    # else
       @all = Allergy.all
    #session[:allergy] = allergy[]
    #session[:alle] = params[:allergy]
    # end

     if params[:back]
       render :text => 'テキスト'
     end

    #  ジャンル選択用

    @s_genre = Genre.select("id,jname")

    # ユーザが選んだ情報を取得する
    @allergy = params[:allergy]
    if logged_in?
       @allergy = current_user.alvalue.split(",")
      # @allergy = [2,3,4]
    else
      # @allergy = [2,3,4]
      # @allergy = params[:allergy]
    end
    #@all = Allergy.all
    #  情報をfindに渡す
    @i = 1;
    if @allergy != nil
      array = Array.new
      @allergy.each.with_index(1) do |u|
        array.push("alvalue NOT like '%,#{u},%'")		end
          sql = "select * from dishes where "
          array.each do |a|
            if @i == 1
            sql = sql + a
            @i = 2
          else
            sql = sql +" or "+ a
         end
       end
       else
         sql = "select * from dishes where id IN"

       end
    @alsql = sql

end


   def find
     # 入力された値から献立番号(料理番号)を検索し、レシピ表示コントローラに渡す

   end


   def question_result
     #  #アレルギー取得（ログイン）
       #  @userall = User.all
       #  user = Array.new
       #  @userall.each do |set|
       #    user.push(set.alvalue",")
       #  end
       #  @user = user
        #アレルギー取得(非ログイン)
       #  Dish.find_by_sql("SELECT * FROM dishes WHERE alvalue NOT LIKE '%id%'")
       #@allergy = [2,3,4]
       #@allergy = session[:allergy]

       #@all = Allergy.all
       @allergy = params[:allergy]
        array = Array.new

        @i = 1;
        if @allergy != nil
          array = Array.new
          @allergy.each.with_index(1) do |u|
            array.push("alvalue NOT like '%,#{u},%'")		end
              sql = "select * from dishes where "
              array.each do |a|
                if @i == 1
                sql = sql + a
                @i = 2
              else
                sql = sql +" or "+ a
             end
           end
           else
             sql = "select * from dishes where id IN"
        end
        @alsql = sql


        #  SQL実行の順番 1208ver
          # => 使用希望食材名からidを取得
          # => 1:アレルギーが入っている料理を省く(まだ)
          # => 2:ジャンル検索
          # => 3:フラグ設定(主菜)
          # => 4:時間の質問(余裕なしだと文章追加あり)
          # => 5:使用食材

             # コネクションを貼る
             con = ActiveRecord::Base.connection
            #  genre = Genre.where(jname: params[:genre]).select("id")


            #使用希望食材を取得し、idを取得
             @mate     = params[:page][:syokuzai]
              if @mate != ''
               #  材料idを取得
                @food_id  = con.select_value('SELECT id FROM foods where fname like "' + @mate + '";')
              end


              #2:ジャンル検索
              #ジャンルid取得
              @genre = params[:genre]

             # 4:時間の質問
             # 時間に余裕があるか否かを尋ねる
             if params[:time][:time] == 'yes'
               # すべての料理表示
               @time = " and recipe like '%step5%'"
             else
               # 時間余裕なし、step数少なめのみ表示
               @time = " and recipe NOT like '%step5%'"
             end

           # => 料理番号の取得 後のために初期値を設定
           @recipe = ''
           # 食材ID設定済みver
           if @mate != '' && @food_id != ''
               @recipe = '(select id from dishes where flag = 0
                                           and genre_id = ' + @genre + @time +
                                           ' and food like "%:[?' + @food_id + '") ;'
#                 @recipe = con.select_rows('select id from dishes where flag = 0
#                                            and genre_id = ' + @genre + @time +
#                                            ' and food like "%:[?' + @food_id + '" ;')
          end
          if @recipe == ''
              # => foodで取得できなかったとき　または　先の時点で食材ID設定出来ずor指定なしver
              # ジャンルと時間の設定のみ
              @recipe = '(select id from dishes where flag = 0
                                          and genre_id = ' + @genre + @time +' );'
#                @recipe = con.select_rows('select id from dishes where flag = 0
#                             and genre_id = ' + @genre + @time +' ;')
          end



          # @recipe = con.select_rows(@alsql + @recipe)


             # 人数の取得
             @people = params[:person][:number]

             # 副菜の指定
             @hukusai = params[:side][:number]



             # ここから情報の格納
             # 配列の設定   料理番号(二次元) 人数 副菜の品数
             result = {ryorinum: @recipe, people: @people, hukusai: @hukusai}

            #  配列で取得できてるかチェックする





    end
 end

app/helpers/manu_pages_helper.rb
module ManuPagesHelper
  def person_choices
    [["1人", 1],
     ["2人", 2],
     ["3人", 3],
     ["4人", 4],
     ["5人", 5],
     ["6人", 6],
     ["7人", 7],
     ["8人", 8],
     ["9人", 9],
     ["10人", 10]
    ]
  end

  def side_choices
    [["なし", 0],
     ["1品", 1],
     ["2品", 2],
     ["3品", 3],
     ["4品", 4],
     ["5品", 5]
    ]
  end

  def zyannru_choices
    [["和食", "japanese"],
    ["洋食", "western"],
    ["中華", "china"]
    ]
  end

  def time_choices
    [["ある", "yes"],
    ["ない", "no"]
    ]
  end

  def main_choices
    [["お肉", "meet"],
     ["お魚", "fish"],
     ["それ以外", "other"]
    ]

  end

end

app/views/manu_pages/_allergy_search.html.erb
<!-- アレルギー取得用 -->


<p>
  <input type="checkbox" name="product[allergie_ids][]" id="product_allergie_ids_1" value="えび">
  <label for="product_allergie_ids_1">えび</label>
  <input type="checkbox" name="product[allergie_ids][]" id="product_allergie_ids_2" value="カニ">
  <label for="product_allergie_ids_2">カニ</label>
  <input type="checkbox" name="product[allergie_ids][]" id="product_allergie_ids_3" value="小麦">
  <label for="product_allergie_ids_3">小麦</label>
</p>

app/views/manu_pages/init.html.erb
<h1><Center>今日の献立を考えます</Center></h1>
<!--
<p>Find me in app/views/manu_pages/menu.html.erb</p>

-->

<Center>


<%= form_tag('question',method: "get") do %>

<!-- アレルギーの有無を聞く -->
  <h4>アレルギーはありますか？</h4>
  <p>

<% @allergie.each.with_index(1) do |set| %>
  <%= check_box_tag('allergy[]',set.id,(set == params[:allergy])) %>
  <%= label_tag 'allergy',set.aname %>
<% end %>


<!-- ラジオボタン未選択時にエラーメッセージを表示 -->
<% flash.each do |message_type, message| %>
<div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>


<!-- フォームボタンなど -->
<p>
  <%= submit_tag "次", name: "check" %>
<% end %>
<%= link_to (button_tag "ホームへ戻る"),
 {:controller => "static_pages" ,:action => "home"},
 {:class => "btn"} %>
</p>



</Center>

<%= render 'layouts/footer' %>

app/views/manu_pages/menu_disp.html.erb
<!--<h1>ManuDisp#menu_disp</h1>
<p>Find me in app/views/manu_disp/menu_disp.html.erb</p>





 <img alt="HO" src="/assets/HO.gif"/>

-->

<div class="hero-text">
  <h1 class="responsive-headline"></h1>
</div>
<br>



<br>

 <%= link_to (button_tag "この献立は気に入らん"),
  {:controller => "manu_pages" ,:action => "question"},
  {:class => "btn"} %>

<%= render 'layouts/footer' %>

app/views/manu_pages/question.html.erb

<%= stylesheet_link_tag    'jquery.bxslider', media: 'all', "data-turbolinks-track" => true %>
<%= stylesheet_link_tag 'akineta-style', media: 'all', 'data-turbolinks-track' => true %>

  <body>

    <div class="container">

      <!--ヘッダーに関する記述---------------------------------------------------------->
          <%= render 'layouts/header' %>
      <!--ヘッダーに関する記述ここまで---------------------------------------------------->

      <!--メインコンテンツに関する記述----------------------------------------------------->
      <main class="contents">

        <div class="contents__inner akineta">

          <!--ここから記述開始-->
          <%= form_tag('/menu/question_result') do %>
          <!--献立の提案に関する記述------------------------------------------>
          <% if logged_in?%>
          <section>
            <h2><i class="fa fa-file-text-o"></i>クッキンマウス君のレシピ提案</h2>
            <p>質問に答えた内容に合わせて献立を提案いたします。</p>
            <div class="bxslider">

          <% else %>
          <section>
            <h2><i class="fa fa-file-text-o"></i>クッキンマウス君のレシピ提案</h2>
            <p>質問に答えた内容に合わせて献立を提案いたします。</p>
            <div class="bxslider">
              <div class="slide_box">
              <p>質問：アレルギーがあるものを選択してください</p>

              <div class="question allergies">
              <% @all.each.with_index(1) do |set,| %>
              <% if (set.id % 9)  == 0 then %>
                  <br>
                  <% end %>
                <p><%= check_box_tag('allergy[]',set.id,(set == params[:allergy])) %>
                  <% if set.id == 7 %>
                  <%= label_tag 'allergy', 'ピーナッツ'%></p>
                  <% else %>
                <%= label_tag 'allergy',set.aname %></p>
                <% end %>
                <% end %>
              </div><!--/.question-->
            </div><!--/.slide_box-->
            <% end %>
              <!--人数指定------------------------------------------------------>
              <div class="slide_box">
              <p>質問：何人分の料理を作りますか？（最大10人まで）</p>
              <div class="question">
                <p class="question-text"><label for="ninnzuu">人数を選択してください</label>
              <%=select :person, :number, person_choices%>
            </p>

              <!--人数指定ここまで---------------------------------------------->
             </div><!--/.question-->
            </div><!--/.slide_box-->

            <div class="slide_box">
              <p>質問：料理のジャンルは？</p>
              <div class="question">

              <p class="question-text"><label for="zyannru">料理のジャンルを選択してください</label>
              <!--選択肢の記述-------------------------------------------------->
              <%= select_tag "genre", options_from_collection_for_select(@s_genre.all,:id,:jname) %>
            </p>
              <!--選択肢の記述ここまで-------------------------------------------->
            </div><!--/.question-->
          </div><!--/.slide_box-->




            <div class="slide_box">
              <p>質問 : 使いたい食材・食べたい食材を１つ記入してください
              <div class="question">
              <!--選択肢の記述-------------------------------------------------->
              <%= text_area :page, :syokuzai, :size =>"50x1", :placeholder => "しいたけ" %></p>
              <!--選択肢の記述ここまで-------------------------------------------->
            </div>
          </div>

          <div class="slide_box">
              <p>質問：調理時間は余裕がありますか？</p>
              <div class="question">

            <!--選択肢の記述-------------------------------------------------->
            <p class="question-text"><label for="time">調理時間は余裕が</label>
              <%=select :time, :time, time_choices%>
          </p>
            <!--選択肢の記述ここまで-------------------------------------------->
          </div><!--/.question-->
        </div><!--/.slide_box-->

            <div class="slide_box">
              <p>質問：副菜の数は？(0品から5品まで)</p>
              <div class="question">
              <!--選択肢の記述-------------------------------------------------->
              <p class="question-text"><label for="side-dish">副菜の数を選択してください(0品から5品まで)</label>
              <%=select :side, :number, side_choices%>
              </p>
              <!--選択肢の記述ここまで-------------------------------------------->
              </div><!--/.question-->
              <%= submit_tag "提案結果を見る！", name: "question_result", :class => "submit" %>
              <% end %>
            </div><!--/.slide_box-->

          </div><!--/.bxslider-->

            <!--質問内容を増やす場合は上のdivコンテンツをコピーしラジオボタンの内容を適宜変更
              質問はスライドしながら答えてもらうので増えても問題なし-->
              <p><%= image_tag '/img/akineta/charcter.png', :alt => 'フライパンとフライ返しを持ったネズミのイラスト', :class => "charcter" %></p>
            </section>
          <!--献立の提案に関する記述ここまで------------------------------------>




        </div><!--/.contents__inner-->
      </main>
<!--メインコンテンツに関する記述ここまで---------------------------------------------->


  <%= render 'layouts/footer' %>
    </div><!--/.container-->

    <script type="text/javascript">
          $(function() {
            $('.bxslider').bxSlider({
              pager: true,
              controls: true,
              infiniteLoop: false,
              nextText: '次の質問に進む',
              prevText: '前の質問に戻る',
              hideControlOnEnd: true,
              mode: 'fade',
            });
          });
        </script>

  </body>

</html>

app/views/manu_pages/question_result.html.erb
<!DOCTYPE html>

<html lang="ja">

  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">  <!--モバイル端末で閲覧するための設定-->
      <meta name="author" content="ヒロコンの愉快な仲間たち" />  <!--サイトの著者-->
      <meta name="keyword" content="献立,レシピ,ご飯" />        <!--サイトの検索キーワード-->
      <meta name="description" content="広島コンピュータ専門学校の" />    <!--サイトの説明文-->
      <% provide(:title, "献立提案結果") %>         <!--サイトのタイトル、ページに合わせて適宜変更-->

      <!--ここからCSSファイルの読み込み--------------------------------------------->
      <%= stylesheet_link_tag    'application', media: 'all', "data-turbolinks-track" => true %>
      <%= stylesheet_link_tag    'top-style', media: 'all', "data-turbolinks-track" => true %>
      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
      <%= csrf_meta_tags %>
      <!--CSSファイルの読み込みここまで--------------------------------------------->

      <!--ショートカットに表示する画像の設定(ファビコン)-------------------------------->
      <link rel="apple-touch-icon" sizes="180x180" href="">
      <link rel="icon" type="image/png" href="" sizes="32x32">
      <link rel="icon" type="image/png" href="" sizes="16x16">
      <!--ショートカットの画像の設定ここまで------------------------------------------>

  </head>

<main class="contents">

        <div class="contents__inner akineta-result">

          <!--献立の提案結果に関する記述------------------------------------------>
          <%=@alsql%>
          <section>
            <h2>献立を提案した結果・・・</h2>
            <p><span>ここに提案する料理名が入ります。</span>がオススメです！</p>
            <p><%= image_tag '/img/top/popular/sample.jpg', :alt => '料理の写真' %></p><!--ここに提案結果の料理の写真が入ります。-->
            <p><%= image_tag '/img/akineta/charcter.png', :alt => 'フライパンとフライ返しを持ったネズミのイラスト' %></p>
          </section>
          <!--献立の提案結果に関する記述ここまで------------------------------------>

          <!-- テスト用 -->
          <%= @recipe%>

          <p><%= link_to "このレシピを見る！", '#' %></p>
          <p><%= link_to "提案をもう一度受ける！", question_path %></p>


        </div><!--/.contents__inner-->


      </main>


<%= render 'layouts/footer' %>
</html>

app/views/manu_pages/result.html.erb
<div>
<%= label_tag 'main',@main.dishname %>
</div>
<div>
<%= image_tag(@main.image) %>
</div>
<div>
<% @link = "/recipe/" + @main.id.to_s %>
<%= link_to 'レシピ', @link %>
</div>
<hr>

<div>
<%= label_tag 'sub1',@sub1.dishname %>
</div>
<div>
<%= image_tag(@sub1.image) %>
</div>
<div>
<% @link = "/recipe/" + @sub1.id.to_s %>
<%= link_to 'レシピ', @link %>
</div>

<hr>

<div>
<%= label_tag 'sub2',@sub2.dishname %>
</div>
<div>
<%= image_tag(@sub2.image) %>
</div>
<div>
<% @link = "/recipe/" + @sub2.id.to_s %>
<%= link_to 'レシピ', @link %>
</div>
<hr>